### ISSUE TITLE
New release on pypi ?

### ISSUE THREAD

**Issue by stuaxo** [mapleoin/undecorated#4]
Hi,
   I'm assuming this version supercedes the version on Pypi - does anything need to happen to do a release there ?

If there's been a handover from the previous owner, it might be a matter of opening a ticket at https://github.com/pypa/warehouse

Cheers
S

**Comment by iartarisi** [comment]
Hey,

The version on pypi is the latest one from `master`: `0.3.0`. I'm the owner there.

Are you having any problems with it?

**Comment by stuaxo** [comment]
No, I was confused by the homepage link https://github.com/mapleoin/undecorated which I now see redirects to here.

**Comment by stuaxo** [comment]
I don't know if it's related, but the travis badge on pypi is broken, as it points at

https://travis-ci.org/mapleoin/undecorated

It might just be a matter of updating the info over there.

**Comment by iartarisi** [comment]
Ah, yeah. Good shout. It seems I need to make a release in order to fix that, though.
