### ISSUE TITLE
Indentation of undecorated/undecorated.py at line 57 and 58

### ISSUE THREAD

**Issue by alexandreCameron** [mapleoin/undecorated#6]
Hi,

I'm not sure that I understand the indentation of `undecorated/undecorated.py` at line 57 and 58.

Why is is:

```python
            if looks_like_a_decorator(cell.cell_contents):
                undecd = undecorated(cell.cell_contents)
                if undecd:
                    return undecd
        else:
            return o
```  

and not:

```python
            if looks_like_a_decorator(cell.cell_contents):
                undecd = undecorated(cell.cell_contents)
                if undecd:
                    return undecd
            else:
                return o
```  
 ?

**Comment by iartarisi** [comment]
Hi

The `else` is for the `for`, not for the `if`. It's a `for/else` block:  
*When the items are exhausted (which is immediately when the sequence is empty or an iterator raises a StopIteration exception), the suite in the else clause, if present, is executed, and the loop terminates.* https://docs.python.org/3.8/reference/compound_stmts.html#for

In this case, the `else` clause isn't required, the `return o` could have just been on a line by itself. But it would have to be indented. On the other hand, the `else` clause might make it more obvious that it would only get executed once the loop is exhausted and draw attention to the fact that the loop has another way to exit (that `return undecd` inside).
